import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { contentPrivacyProblems, assetPrivacyProblems, emailPrivacyProblems, RESTRICTED_ASSET_FINGERPRINTS } from '../../src/lib/privacy.mjs';
import { createHash } from 'node:crypto';
import { checkDist } from '../check-dist.mjs';
const draft = { settings: { noindex: true, siteUrl: 'https://<username>.github.io' }, profile: { headshot: '/img/headshot-placeholder.webp', cvUrl: '' }, contact: { emailConfirmed: false, emailUser: 'placeholder', emailDomain: 'invalid.invalid' } };
assert.deepEqual(contentPrivacyProblems(draft), []);
assert.ok(contentPrivacyProblems({ ...draft, contact: { ...draft.contact, emailConfirmed: true } }).length);
assert.ok(contentPrivacyProblems({ ...draft, settings: { ...draft.settings, noindex: false } }).length);
const confirmed = { ...draft, settings: { noindex: false, siteUrl: 'https://portfolio.example-owner.dev' }, profile: { headshot: '', cvUrl: '' }, contact: { emailConfirmed: true, emailUser: 'owner', emailDomain: 'example-owner.dev' } };
assert.deepEqual(contentPrivacyProblems(confirmed), []);
assert.ok(emailPrivacyProblems('<span data-u="placeholder" data-d="invalid.invalid"></span>', draft.contact).length);
assert.ok(emailPrivacyProblems('<a href="mailto:placeholder&#64;invalid.invalid">Email</a>', draft.contact).length);
assert.deepEqual(emailPrivacyProblems('const href = "mailto:"; document.querySelector(".js-mail");', draft.contact), []);
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'portfolio-privacy-'));
try {
  fs.writeFileSync(path.join(root, 'index.html'), '<meta name="robots" content="noindex, nofollow"><p>Contact details pending confirmation.</p>');
  fs.writeFileSync(path.join(root, '404.html'), '<meta name="robots" content="noindex, nofollow">');
  fs.writeFileSync(path.join(root, '.nojekyll'), '');
  fs.writeFileSync(path.join(root, 'font.woff2'), 'fixture');
  assert.deepEqual(checkDist(draft, root), []);
  const knownHashes = RESTRICTED_ASSET_FINGERPRINTS.map(({ sha256 }) => sha256);
  assert.ok(knownHashes.includes('5ad0f3d9d2a2363016ae5d27d91b2b5ed0651be5796e535b5984da70b458d1e3'));
  assert.ok(knownHashes.includes('838b2193cb74ded3117077d29c49a5fb964ecc32fdafa2e0de3d125bf40af4a2'));
  const restrictedFixture = Buffer.from('historical binary fixture');
  const restrictedHash = createHash('sha256').update(restrictedFixture).digest('hex');
  fs.writeFileSync(path.join(root, 'renamed.bin'), restrictedFixture);
  assert.ok(assetPrivacyProblems(root, { restrictedAssetSet: new Map([[restrictedHash, 'historical OG']]) }).some((p) => p.includes('historical OG')));
  fs.unlinkSync(path.join(root, 'renamed.bin'));
  const publicDir = fileURLToPath(new URL('../../public/', import.meta.url));
  fs.copyFileSync(path.join(publicDir, 'og-image.png'), path.join(root, 'renamed-draft-preview.bin'));
  assert.deepEqual(assetPrivacyProblems(root), []);
  assert.ok(assetPrivacyProblems(root, { publicMode: true }).some((p) => p.includes('renamed-draft-preview.bin')));
  fs.unlinkSync(path.join(root, 'renamed-draft-preview.bin'));
  assert.deepEqual(assetPrivacyProblems(publicDir), []);
  fs.writeFileSync(path.join(root, 'portrait.webp'), 'portrait fixture');
  const portraitHash = createHash('sha256').update('portrait fixture').digest('hex');
  assert.ok(assetPrivacyProblems(root, { publicMode: true, draftHeadshotHash: portraitHash }).some((p) => p.includes('portrait.webp')));
  fs.unlinkSync(path.join(root, 'portrait.webp'));
  fs.writeFileSync(path.join(root, 'index.html'), '<output data-u="owner" data-d="example-owner.dev"><noscript>owner [at] example-owner [dot] dev</noscript></output>');
  assert.deepEqual(checkDist(confirmed, root), []);
  assert.ok(checkDist(draft, root).some((p) => p.includes('unconfirmed email')));
  fs.writeFileSync(path.join(root, 'index.html'), '<output data-u="wrong" data-d="example-owner.dev"><noscript>wrong [at] example-owner [dot] dev</noscript></output>');
  assert.ok(checkDist(confirmed, root).some((p) => p.includes('inconsistent')));
  fs.writeFileSync(path.join(root, 'index.html'), '<meta name="robots" content="noindex"><meta property="og:image" content="https://host.dev/og-image.png">');
  assert.ok(checkDist(draft, root).some((p) => p.includes('placeholder siteUrl')));
} finally { fs.rmSync(root, { recursive: true, force: true }); }
console.log('✓ privacy guard regressions passed');
